import type { Script } from '@/lib/models';

/**
 * Strip HTML tags and decode common entities from rich-text block content.
 */
function stripHtml(html: string): string {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .trim();
}

/**
 * Convert a Script to Fountain screenplay format.
 *
 * Fountain is a plain-text screenplay markup language (https://fountain.io/).
 * Scene headings use INT./EXT. notation derived from `scene.isEXT` and
 * `scene.isDay` flags. Block text is included as action lines.
 */
export function scriptToFountain(script: Script): string {
  const lines: string[] = [
    `Title: ${script.title}`,
    `Credit: Generated by Dramo`,
    '',
  ];

  const orderedScenes = script.scenes.slice().sort((a, b) => a.order - b.order);

  for (const scene of orderedScenes) {
    const location = scene.isEXT ? 'EXT.' : 'INT.';
    const timeOfDay = scene.isDay === false ? 'NIGHT' : 'DAY';
    lines.push(`${location} ${scene.title.toUpperCase()} - ${timeOfDay}`, '');

    for (const block of scene.content) {
      const text = stripHtml(block.text);
      if (text.trim()) {
        lines.push(text, '');
      }
    }
  }

  return lines.join('\n');
}

/**
 * Convert a Script to a CSV dialogue table with columns: 场景, 角色, 台词.
 *
 * Extracts dialogue lines from block content using a pattern that matches
 * a speaker name (2+ Chinese or uppercase Latin characters) followed by a
 * newline and dialogue text.
 *
 * Returns a UTF-8 CSV string (with BOM prefix for Excel Chinese-char support).
 */
export function scriptToCsv(script: Script): string {
  const rows: string[][] = [['场景', '角色', '台词']];

  const orderedScenes = script.scenes.slice().sort((a, b) => a.order - b.order);

  for (const scene of orderedScenes) {
    for (const block of scene.content) {
      if (!block.text) continue;

      const text = stripHtml(block.text);
      // Match patterns like:
      //   CHARACTER_NAME\nDialogue text
      // Speaker: 2+ Chinese chars OR 2+ uppercase Latin letters
      const dialoguePattern = /([A-Z一-鿿]{2,})\n(.+)/g;
      let match: RegExpExecArray | null;

      while ((match = dialoguePattern.exec(text)) !== null) {
        rows.push([scene.title, match[1], match[2]]);
      }
    }
  }

  // UTF-8 BOM ensures Excel correctly displays Chinese characters
  const bom = '﻿';
  const csv = rows
    .map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(','))
    .join('\n');

  return bom + csv;
}
